# Site settings
title: dery febriantara - Web Developer
description: "A blog about a failed programmer ..."
baseurl: "" # for test: remove string '/space-jekyll-templa' to ''
url: "https://deryfebriantara.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'
# User settings
username: dery febriantara
user_title: Lorem Ipsum - FrontEnd
email: deryfebriantara@gmail.com
twitter_username: deryfebriantara
github_username:  deryfebriantara
gplus_username:  deryfebriantara
disqus_username: deryfebriantara-github-io

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
  - title: series
    url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
  - name: nodejs
    url: https://github.com/angularjs
  - name: angularjs
    url: https://github.com/angularjs
  - name: angular
    url: https://github.com/angular
  - name: ionic v1
    url: https://github.com/ionic3
  - name: ionic 3
    url: https://github.com/ionic3
  - name: symfony2
    url: https://github.com/symfony2
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
